fork=no
stderr=yes
loglevel=3
sip_ip=127.0.0.1
media_ip=127.0.0.1
sip_port=5066
rtp_low_port=30000
rtp_high_port=40000
plugin_path=core/lib
plugin_config_path=t/xdsm
load_plugins=wav;gsm;opus;sbc;dsm;cc_dsm
application=sbc
send_491_on_pending_session_leg=yes
