# Python version: 2.3, 2.4, 2.5, and 3.x
#
PYTHON_VERSION ?= $(shell python2 -c 'import sys;print sys.version[0:3]')
PYTHON_VERSION ?= $(shell python -c 'import sys;print sys.version[0:3]')
PYTHON_VERSION ?= $(shell python3 -c 'import sys;print("%d.%d" % (sys.version_info.major,sys.version_info.minor))')


PY_VER = $(PYTHON_VERSION)
PY_EXE = python$(PY_VER)

# For flite text-to-speech set TTS = y
#
TTS ?= n

FLITE_DIR = /usr/src/flite-1.2-release
ALT_FLITE_DIR = /usr/include/flite
